import {BattleUI} from '../../src/battle-ui.js';
import {LibraryUI} from '../../src/library-ui.js';
import {InventoryUI} from '../../src/inventory-ui.js';
import {SLOT_LABELS} from '../../src/inventory-proof.js';
export function game(){
 const slots={weapon:'兵刃',head:'头部',body:'上身',legs:'腿部',feet:'足部',accessory:'饰品',artifact:'法宝',special:'特殊'};
 window.actions=[];window.visits=[];window.renderRows=()=>{};window.bag=Object.keys(slots).flatMap((slot,index)=>[{name:'同名'+slots[slot],identity:'item-'+(index*2+1),slot,quality:'100',quantity:1,equipped:false},{name:'同名'+slots[slot],identity:'item-'+(index*2+2),slot,quality:'100',quantity:1,equipped:true}]);bag.push({name:'矿石',identity:'',slot:null,quantity:15001,quality:null,equipped:false});window.shopAvailable=true;window.saved=true;window.mismatch=false;
 const main=document.querySelector('main');const art=i=>'<span class="item-glyph '+(i.identity?'equipment':'material')+'"></span>';
 function details(i,shop=false){visits.push(shop?'sale-detail':'equipment-detail');
  const d=document.createElement('dialog');const render=()=>{d.innerHTML='<header><h2>'+(shop?'售出物品':i.equipped?'已装备器物':'物品详情')+'</h2><button aria-label="关闭窗口">X</button></header><div class="dialog-body"><div class="item-detail-title"><span class="eyebrow">'+(slots[i.slot]??'材料')+'</span><h2>'+i.name+'</h2><div class="quality">'+(i.identity?'品质 '+i.quality+' · #'+i.identity.slice(5):'')+'</div></div><div class="bag-comparison">气血 100 → 120</div>'+(shop?'<div class="item-valuation"><span>单价</span><strong>100 灵石</strong></div>'+(!i.identity?'<label>交易数量<input type="number" value="1" max="'+Math.min(i.quantity,10000)+'"></label>':'')+'<button class="sell">售出</button>':'<div class="bag-detail-actions"><button>'+(i.equipped?'卸下':'替换装备')+'</button></div>')+'</div>';
   d.querySelector('header button').onclick=()=>d.remove();
   if(shop)d.querySelector('.sell').onclick=async()=>{const q=i.identity?1:Number(d.querySelector('input').value);actions.push(['sell',i.identity||'ore',q]);d.querySelector('.sell').disabled=true;if(window.tradeDelay)await new Promise(r=>setTimeout(r,tradeDelay));if(window.noSale){d.querySelector('.sell').disabled=false;return;}if(i.identity)bag=bag.filter(x=>x!==i);else i.quantity-=q;if(window.reorder)bag.reverse();renderRows();d.querySelector('.sell').disabled=false;if(window.afterSale)window.afterSale();if(!i.identity&&d.querySelector('input'))d.querySelector('input').max=String(Math.min(i.quantity,10000));document.querySelector('footer.statusbar').textContent=saved?'本地存档已就绪':'正在保存';if(i.identity||i.quantity===0)d.remove();};
   else d.querySelector('.bag-detail-actions button').onclick=()=>{if(i.equipped)throw new Error('no unequip allowed');actions.push(['equip',i.identity]);for(const x of bag)if(x.slot===i.slot)x.equipped=false;i.equipped=true;render();};
  };render();document.body.append(d);d.showModal();
 }
 window.show=tab=>{visits.push(tab);
  document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('selected',b.textContent===tab));
  if(tab==='游历'){main.innerHTML='<div class="location-view"><h1>千渠埠</h1><div class="location-safety">安全区 可调息</div><div class="place-actions"><button>调息</button></div><nav class="place-links" aria-label="当地往来">'+(shopAvailable?'<button class="shop-entry"><svg></svg><span><strong>四海商盟·千渠商会</strong><small>货物买卖</small></span></button>':'')+'<button><strong>商盟寄售</strong><small>四海共通货池</small></button></nav></div>';main.querySelector('.shop-entry')?.addEventListener('click',shop);return;}
  main.innerHTML='<div class="inventory-view"><div class="page-heading"><h1>行囊</h1></div><div class="bag-equipment expanded"><div class="bag-equipment-rack"></div></div><div class="bag-grid"></div></div>';
  for(const [key,label] of Object.entries(slots)){const i=bag.find(x=>x.slot===key&&x.equipped),b=document.createElement('button');b.className='bag-equipment-slot '+(i?'filled':'vacant');b.innerHTML='<span class="bag-slot-label">'+label+'</span><strong>'+(i?.name??'未装备')+'</strong>';b.onclick=()=>{if(i)details(i);else throw new Error('do not click empty')};main.querySelector('.bag-equipment-rack').append(b);}
  for(const i of bag.filter(i=>!i.equipped&&i.quantity>0)){const b=document.createElement('button');b.className='bag-item';b.setAttribute('aria-label','查看'+i.name+'，'+(i.identity?'品质'+i.quality+'，编号'+i.identity:'持有'+i.quantity+'份')+'，回收单价100灵石');b.innerHTML=art(i)+'<strong>'+i.name+'</strong>';b.onclick=()=>details(i);main.querySelector('.bag-grid').append(b);}
 };
 function shop(){visits.push('shop');main.innerHTML='<div class="page service-page"><div class="eyebrow">千渠埠</div><h1>四海商盟·千渠商会</h1><button aria-label="返回当地">返回</button><div class="shop-view"><div class="tabs" role="tablist" aria-label="商店买卖"><button role="tab" aria-selected="true">购入</button><button class="sell-tab" role="tab" aria-selected="false">售出</button></div><input type="search" aria-label="查找交易物品" value="上次搜索"><div class="entry-list"></div></div></div>';main.querySelector('[aria-label="返回当地"]').onclick=()=>show('游历');
  const rows=window.renderRows=()=>{const root=main.querySelector('.entry-list');root.replaceChildren();if(main.querySelector('.sell-tab').getAttribute('aria-selected')!=='true')return;
   const term=main.querySelector('input[type=search]').value;
   for(const i of bag.filter(i=>i.quantity>0&&i.name.includes(term))){const row=document.createElement('div'),b=document.createElement('button');b.className='entry';b.innerHTML='<span class="entry-name"><strong>'+i.name+'</strong><small>品质 '+i.quality+'</small></span><span class="entry-price">100 灵石</span><span class="entry-count">'+(i.equipped?'<svg aria-label="已装备"></svg>':i.identity?'#'+i.identity.slice(5):'×'+(window.rounded&&i.quantity>=10000?(Math.floor(i.quantity/100)/100)+'万':i.quantity))+'</span>';b.onclick=()=>details(mismatch?{...i,identity:'item-999'}:i,true);row.append(b);if(!i.identity){const quick=document.createElement('button');quick.textContent='全部';quick.setAttribute('aria-label','售出全部'+i.name);quick.onclick=()=>actions.push(['UNEXPECTED quick sell']);row.append(quick);}root.append(row);}
  };
  for(const tab of main.querySelectorAll('[role=tab]'))tab.onclick=()=>{if(window.ignoreSaleTab)return;for(const t of main.querySelectorAll('[role=tab]'))t.setAttribute('aria-selected',String(t===tab));rows();};
  main.querySelector('input[type=search]').oninput=rows;
 }
 document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>show(b.textContent));show('游历');
}
export async function setup(browser,{Adapter=InventoryUI,realWait=false}={}){const page=await browser.newPage();await page.setContent('<aside class="character-panel"><div class="discord-profile"><h3>测试修士</h3></div><div><span>气血</span><span>5 / 100</span></div></aside><nav class="central-nav"><button>游历</button><button>行囊</button></nav><main data-region="百渠泽地" data-location="千渠埠"></main><footer class="statusbar">本地存档已就绪</footer>');await page.evaluate(game);
 const ui=new BattleUI(page,{characterName:'测试修士',actionDelaySeconds:0.3,target:{regionName:'北',stageName:'山'}},{actionDelaySeconds:2,responseTimeoutSeconds:1},()=>{},new AbortController().signal);ui.ensureApp=async()=>page.mainFrame();
 const reader=new LibraryUI(ui,realWait?{}:{wait:async()=>{}});const knowledge={items:[...Object.entries(SLOT_LABELS).map(([slot,name])=>({id:slot,name:'同名'+name,slot})),{id:'ore',name:'矿石'}]};const adapter=new Adapter(ui,{reader,knowledge});return {page,ui,adapter};}
